plugins {
    id 'com.android.application'
}

android {
    namespace 'com.entrena360.garmin'
    compileSdk 35

    defaultConfig {
        applicationId "com.entrena360.garmin"
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName "2.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.activity:activity:1.10.1'
}
